### PR TITLE
DB-2860 add default storage size and args for prometheus

### PR DESCRIPTION
**Pull request by sincejune**
When the user changes the retention time via args, he'd better also append the retention size. Because The `services: prometheus: containerConfig: args` in values.yml will override this one.

**NOTE: All existing deployment whose Prometheus pod storage is not `100Gi` will be affected.**

### CODE REVIEW

**Comment by adadb** [comment]
why is --storage.tsdb.retention.size=60GB but storage:size is 100Gi ?

**Review by adadb — APPROVED** [review]
nvm I sort of get it now. I guess one is disk size, the other is container size.

**Comment by sincejune** [comment]
`100Gi` is the disk size. I only set `60Gi` for `storage.tsdb.retention.size` cuz:
> --storage.tsdb.retention.size: [EXPERIMENTAL] This determines the maximum number of bytes that storage blocks can use (note that this does not include the WAL size, which can be substantial).

ref: https://prometheus.io/docs/prometheus/latest/storage/

**Review by rluidash — APPROVED** [review]
reviewed .. default prometheus disk set to 100G

**Review by khou — APPROVED** [review]

**Pull request merged**
