### PR TITLE
kafka: multi brokers support

### PR DESCRIPTION
**Pull request by SinceJune**
If we don't force assign `KAFKA_BROKER_ID`, Kafka will register broker ID after 1000.

And then we modify the replicas to 3.

    kafka:
      replicas: 3
      image:
        dashbase/kafka:nightly
      ...

Kubernetes will luanch 3 Kafka pods and register all of them into zookeeper.

    [zk: localhost:2181(CONNECTED) 2] ls /brokers/ids
    [1003, 1002, 1001]

when you delete the one pod, kubernetes will recreate that pod, and register the same broker ID into zookeeper.

    ➜  ~ kc delete po kafka-0 -n release
    pod "kafka-0" deleted
    
    ...
    
    [zk: localhost:2181(CONNECTED) 3] ls /brokers/ids
    [1002, 1001]
    [zk: localhost:2181(CONNECTED) 4] ls /brokers/ids
    [1003, 1002, 1001]

I had test send data into `kafka-bootstrap`, and it works.

**Pros:**

1. easily configure, It's for us to reduce/increase Kafka brokers.
2. No big changes to our dashbase-k8s template
3. It's backward compatibility.

**Discussion**

I don't know why we force assigned KAFKA_BROKER_ID before.  This thing I'm not sure may need your answer.
@khou

### CODE REVIEW

**Comment by keitaf** [comment]
I believe we hard-coded `KAFKA_BROKER_ID` because the auto-generated broker ID like `1000` isn't as stable (at least on swarm).

Instead of relying on auto-generated broker ID, can we use `BROKER_ID_COMMAND` to get the broker ID from the host name? In k8s StatefulSet, the hostname is `{service name}-{replica number}` where `replica number` is 0, 1, 2..., so we can extract the replica number and use it as broker ID. I remember this is what Postmates guy suggested.

**Comment by khou** [comment]
What Keita mentioned is the exact reason we hard coded.

Some context was we would do an upgrade that required a restart for single broker Kafka. Originally the broker was 1001, but after restart, it got a new ID, registered to ZK, but alias for “kafka” in swarm was stuck on 1001 and not 1002, so all Dashbase services could not connect.

If this issue doesnt exist in K8s, then it’s actually better that we dont give the ID. However we need to make sure it doesnt exist. Try deleting the pods out of order, and multiple times, with only 2 replica. And delete both pods at the same time. I think you may see something weird. 

Did you get to try partition rebalancing?

**Comment by SinceJune** [comment]
Yes, I had tested this part. I test one-broker kafka and then delete that pod multi times, and table seems works fine.

Also I had created 3 kafka pods, and kill them randomly, their Kafka Broker ID won't change.

I believe it's because Kakfa stored it's broker-id into `meta.properties`. When Kafka restart, It will read `meta.properties.yml` and register id in that file.
When I change this file and restart Kafka, broker id in zookeeper changes. 

    bash-4.4# more /dashbase/kafka/data/meta.properties
    #
    #Wed Nov 07 07:48:10 GMT 2018
    version=0
    broker.id=1001
    bash-4.4#

**Comment by SinceJune** [comment]
Since I set `replicas` more than 1, kafka will automatically enable multi-broker mode.

Kafka will create an auto-generated ID and register to zookeeper.

I do believe the auto-generated ID won't change while kafka restarts (at least on k8s) because kafka will read broker-id the `meta.properties` if this file exists on the local volume. (If broker-id conflict, kafka will fail in loop).


But I agreed to use `BROKER_ID_COMMAND` to force assign broker-id. Looks like it's the most violent and security solution. (Because I don't know why it's problematic on swarm).

I added this line to k8s templates.

    BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2+1}'"

As @keitaf said:

> In k8s StatefulSet, the hostname is {service name}-{replica number}

when the first kafka pod created, it has the hostname `kafka-0`, I add `+1` into this command let the template have backward compatibility(we force assign broker-id to `1` before). Thus the `kafka-0` will have broker-id `1`. the `kafka-1` will have broker-id `2`, etc.


#### But it is not enough. We want high availability on Kafka.

What we have to do:

1. add `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR` 
   > The replication factor for the offsets topic (set higher to ensure availability). Internal topic creation will fail until the cluster size meets this replication factor requirement.

   If leave `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTO` to `1`, kafka will replying the first kafka broker, `kafka-0` I mean. If `kafka-0` down, the whole kafka will down. Because `kafka-0` stores all offsets information, kafka won't recovery without those information.
   
2. add `KAFKA_DEFAULT_REPLICATION_FACTOR`
   > default replication factors for automatically created topics
   Same as `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR`. But only for automatically created topics.

example:

        kafka:
          replicas: 4
          image: dashbase/kafka:nightly
          containerConfig:
            resources:
              limits:
                cpu: "2"
              requests:
                cpu: 100m
          storage:
            class: "dashbase-data"
            size: "500Gi"
          environment:
            KAFKA_LOG_RETENTION_HOURS: "4"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "3"
            KAFKA_DEFAULT_REPLICATION_FACTOR: "3"

With bigger REPLICATION_FACTOR comes great high availability, but brings more things kafka need to work.

These two environments should be added into values.yml.

**Pull request merged**
