### PR TITLE
add helm test suit

### PR DESCRIPTION
**Pull request by joway**
## Purpose

Add standard output yaml to validate out charts works as we expect.

If this test suit applied, we may need to change the test case every time we changed our charts. It sounds annoying but the test script will output diff detail friendly to help us debug it and write right test case yaml. On the other hand, it will help us 100% knows our template outputs, which is very important when charts grow too larger and more difficult to understand in the feature.

## Setup

```
pip install -r requirements.txt
```

## Usage

```
python checker.py ./dashbase/
```

output:
```
====== Pass: ./dashbase//tests/default/deployment/proxy.yaml ======
====== Pass: ./dashbase//tests/default/horizontalpodautoscaler/proxy.yaml ======
====== Pass: ./dashbase//tests/default/statefulset/web.yaml ======
====== Pass: ./dashbase//tests/default/service/zookeeper.yaml ======
====== Pass: ./dashbase//tests/default/statefulset/table-default-p1.yaml ======
====== Pass: ./dashbase//tests/test-https/statefulset/table-default-p0.yaml ======
```

### CODE REVIEW

**Comment by joway** [comment]
When tests failed, it will show you the diff to help you debug, looks like:

image

**Comment by SinceJune** [comment]
we're limited to add one single test per package in this branch.

I think it would be nice if I can add much more tests into one package.

**Comment by SinceJune** [comment]
we're limited to add one single test per package in this branch.

I think it would be nice if I can add much more tests into one package.

**Comment by joway** [comment]
@keitaf @khou do you have any advice?

**Comment by joway** [comment]
@keitaf @khou do you have any advice?

**Comment by joway** [comment]
@keitaf @khou do you have any advice?

**Pull request merged**
