### PR TITLE
DB-3397 add flag to use GitHub container registry images

### PR DESCRIPTION
**Pull request by sincejune**
There're several types of images we used in the dashbase chart.

### Dashbase common services
**Solution:** I added one flag in `values.yml` to control the image. When we change `imageRegistry` to `ghcr.io`, all these services will use github images.
Affected services: indexer, searcher, table_manager...

### Dashbase stable services
We hardcoded some stable services' images in values.yml as we don't want to restart them anymore.
**Solution:**  I didn't modify these values in `values.yml`.
Affected services: elasticsearch, zookeeper, Kafka
### Community images
We used some community images, such as pushgateway, influxdb, busybox. They're all hardcoded in values.yml which is not templatable.
**Solution:** For these images, I migrated them to GitHub manually and modified the chart to use GitHub ones:
1. ghcr.io/dashbase/busybox:latest => Mirror of busybox:latest
2. ghcr.io/dashbase/pushgateway:v1.0.1 => Mirror of prom/pushgateway:v1.0.1
3. ghcr.io/dashbase/influxdb:1.6.2-alpine => Mirror of influxdb:1.6.2-alpine

### Some other images in the dependency chart.
1. Presto.
**Solution:**  I modified presto chart to use GitHub images directly for now. 
2. busybox (used in ETCD operator dchart).
**Solution:**  I didn't modify them as it will cause restarts.

#### Other changes
Modified `imagePullPolicy` of indexer from `Always` to `IfNotPresent`

Tested locally.

### CODE REVIEW

**Review by javasoze — APPROVED** [review]

**Comment by sincejune** [comment]
Perhaps we can rollback `busybox` to use dockerhub official image but I don't know if official images are also rate-limited. Values.yml doesn't support templating which makes the stuff really complicated.

**Review by keitaf — APPROVED** [review]
looks like `busybox` is also rate limited.
```
$ TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/busybox:pull" | jq -r .token)
$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/library/busybox/manifests/latest
HTTP/1.1 200 OK
Content-Length: 2775
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:33d52c5dc29a0c722573420e56e653a9ed7b849a738345b6903925a5f5a6eceb
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:33d52c5dc29a0c722573420e56e653a9ed7b849a738345b6903925a5f5a6eceb"
Date: Tue, 17 Nov 2020 22:49:53 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: 250;w=21600
RateLimit-Remaining: 250;w=21600
```

It's annoying that we need to clone community images onto Github...

**Review by natalie-arsky — APPROVED** [review]

**Comment by sincejune** [comment]
This PR will actually restart all apis/searchers/indexers due to the initial container image change even if you didn't upgrade them. Is it ok for you? @khou

**Review by rluidash — APPROVED** [review]
LGTM

**Review by khou — APPROVED** [review]
The change for kafka image will not make it restart right? Let's make sure this doesn't cause Kafka to restart.

**Comment by sincejune** [comment]
The kafka image is hardcode in values.yml and I didn't change that, so it won't restart.

**Pull request merged**
